# Generated by Django 5.0 on 2024-10-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0002_doador_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(default=0, max_length=8)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='doador',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doador',
            name='nome',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
